template: true   # required for local templates
valuesFilePath: ./values.yml

resources: 
  - name: gosvc_promoted_build_info
    type: BuildInfo
    configuration:
      # sourceArtifactory: myArtifactory
      sourceArtifactory: {{ .Values.artifactoryIntegration }}
      buildName: dbp_build
      buildNumber: 1    

  - name: release_bundle
    type: ReleaseBundle
    configuration:
      #sourceDistribution: myDist
      sourceDistribution:  {{ .Values.distributionIntegration }}
      name: demo_rb
      version: v1.0.0

  - name: signed_bundle
    type: ReleaseBundle
    configuration:
      #sourceDistribution: myDist
      sourceDistribution:  {{ .Values.distributionIntegration }}
      name: demo_rb
      version: v1.0.0

  - name: distribution_rules
    type: DistributionRule
    configuration:
      #sourceDistribution: myDist
      sourceDistribution:  {{ .Values.distributionIntegration }}
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"     

pipelines:
  - name: cd_demo_release_mgmt
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo_rb
          releaseBundleVersion: v1.0.${run_number}
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: gosvc_promoted_build_info
              trigger: false
          outputResources:
            - name: release_bundle
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points

      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: release_bundle
          outputResources:
            - name: signed_bundle

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_bundle
            - name: distribution_rules 
