template: true   # required for local templates
valuesFilePath: ./values.yml

resources: 
  - name: gosvc_promoted_build_info
    type: BuildInfo
    configuration:
      #sourceArtifactory: Artifactory_integration_dist
      sourceArtifactory: {{ .Values.artifactoryIntegration }}
      buildName: demo_pipeline_build                                    # Name of the Build repo from where we are going to look for the build info for creating the RB
      buildNumber: 4    

  - name: release_bundle
    type: ReleaseBundle
    configuration:
      #sourceDistribution: Distribution_integration
      sourceDistribution:  {{ .Values.distributionIntegration }}
      name: demo_rb
      version: v1.0.0

  - name: signed_bundle
    type: ReleaseBundle
    configuration:
      #sourceDistribution: Distribution_integration
      sourceDistribution:  {{ .Values.distributionIntegration }}
      name: demo_rb
      version: v1.0.0

  - name: distribution_rules
    type: DistributionRule
    configuration:
      #sourceDistribution: Distribution_integration
      sourceDistribution:  {{ .Values.distributionIntegration }}
      serviceName: "*"
      siteName: "cumminspocus"
      cityName: "*"
      countryCodes:
        - "*"     

pipelines:
  - name: cd_demo_release_build
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo_rb
          releaseBundleVersion: v1.0.${run_number}
          dryRun: false
          sign: false
          description: "Automate Release Bundle creation and distribution"
          inputResources:
            - name: gosvc_promoted_build_info
              trigger: false
          outputResources:
            - name: release_bundle
          releaseNotes:
            syntax: markdown
            content: |
              ## Test Release bundle Automation
                * Tesung Release Bundle creation through pipeline
                * Signing RB
                * Distribute Release Bundle

      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: release_bundle
          outputResources:
            - name: signed_bundle

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_bundle
            - name: distribution_rules 
